// CARD DECK ARRAY

export const cardDeck = [
  {
    cardType: "A",
    cardValue: 11,
    suit: "spades",
    cardImage: "../cardImages/spades-A.png",
  },
  {
    cardType: "2",
    cardValue: 2,
    suit: "spades",
    cardImage: "../cardImages/spades-2.png",
  },
  {
    cardType: "3",
    cardValue: 3,
    suit: "spades",
    cardImage: "../cardImages/spades-3.png",
  },
  {
    cardType: "4",
    cardValue: 4,
    suit: "spades",
    cardImage: "../cardImages/spades-4.png",
  },
  {
    cardType: "5",
    cardValue: 5,
    suit: "spades",
    cardImage: "../cardImages/spades-5.png",
  },
  {
    cardType: "6",
    cardValue: 6,
    suit: "spades",
    cardImage: "../cardImages/spades-6.png",
  },
  {
    cardType: "7",
    cardValue: 7,
    suit: "spades",
    cardImage: "../cardImages/spades-7.png",
  },
  {
    cardType: "8",
    cardValue: 8,
    suit: "spades",
    cardImage: "../cardImages/spades-8.png",
  },
  {
    cardType: "9",
    cardValue: 9,
    suit: "spades",
    cardImage: "../cardImages/spades-9.png",
  },
  {
    cardType: "10",
    cardValue: 10,
    suit: "spades",
    cardImage: "../cardImages/spades-10.png",
  },
  {
    cardType: "J",
    cardValue: 10,
    suit: "spades",
    cardImage: "../cardImages/spades-J.png",
  },
  {
    cardType: "Q",
    cardValue: 10,
    suit: "spades",
    cardImage: "../cardImages/spades-Q.png",
  },
  {
    cardType: "K",
    cardValue: 10,
    suit: "spades",
    cardImage: "../cardImages/spades-K.png",
  },
  {
    cardType: "A",
    cardValue: 11,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-A.png",
  },
  {
    cardType: "2",
    cardValue: 2,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-2.png",
  },
  {
    cardType: "3",
    cardValue: 3,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-3.png",
  },
  {
    cardType: "4",
    cardValue: 4,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-4.png",
  },
  {
    cardType: "5",
    cardValue: 5,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-5.png",
  },
  {
    cardType: "6",
    cardValue: 6,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-6.png",
  },
  {
    cardType: "7",
    cardValue: 7,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-7.png",
  },
  {
    cardType: "8",
    cardValue: 8,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-8.png",
  },
  {
    cardType: "9",
    cardValue: 9,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-9.png",
  },
  {
    cardType: "10",
    cardValue: 10,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-10.png",
  },
  {
    cardType: "J",
    cardValue: 10,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-J.png",
  },
  {
    cardType: "Q",
    cardValue: 10,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-Q.png",
  },
  {
    cardType: "K",
    cardValue: 10,
    suit: "diamonds",
    cardImage: "../cardImages/diamonds-K.png",
  },
  {
    cardType: "A",
    cardValue: 11,
    suit: "clubs",
    cardImage: "../cardImages/clubs-A.png",
  },
  {
    cardType: "2",
    cardValue: 2,
    suit: "clubs",
    cardImage: "../cardImages/clubs-2.png",
  },
  {
    cardType: "3",
    cardValue: 3,
    suit: "clubs",
    cardImage: "../cardImages/clubs-3.png",
  },
  {
    cardType: "4",
    cardValue: 4,
    suit: "clubs",
    cardImage: "../cardImages/clubs-4.png",
  },
  {
    cardType: "5",
    cardValue: 5,
    suit: "clubs",
    cardImage: "../cardImages/clubs-5.png",
  },
  {
    cardType: "6",
    cardValue: 6,
    suit: "clubs",
    cardImage: "../cardImages/clubs-6.png",
  },
  {
    cardType: "7",
    cardValue: 7,
    suit: "clubs",
    cardImage: "../cardImages/clubs-7.png",
  },
  {
    cardType: "8",
    cardValue: 8,
    suit: "clubs",
    cardImage: "../cardImages/clubs-8.png",
  },
  {
    cardType: "9",
    cardValue: 9,
    suit: "clubs",
    cardImage: "../cardImages/clubs-9.png",
  },
  {
    cardType: "10",
    cardValue: 10,
    suit: "clubs",
    cardImage: "../cardImages/clubs-10.png",
  },
  {
    cardType: "J",
    cardValue: 10,
    suit: "clubs",
    cardImage: "../cardImages/clubs-J.png",
  },
  {
    cardType: "Q",
    cardValue: 10,
    suit: "clubs",
    cardImage: "../cardImages/clubs-Q.png",
  },
  {
    cardType: "K",
    cardValue: 10,
    suit: "clubs",
    cardImage: "../cardImages/clubs-K.png",
  },
  {
    cardType: "A",
    cardValue: 11,
    suit: "hearts",
    cardImage: "../cardImages/hearts-A.png",
  },
  {
    cardType: "2",
    cardValue: 2,
    suit: "hearts",
    cardImage: "../cardImages/hearts-2.png",
  },
  {
    cardType: "3",
    cardValue: 3,
    suit: "hearts",
    cardImage: "../cardImages/hearts-3.png",
  },
  {
    cardType: "4",
    cardValue: 4,
    suit: "hearts",
    cardImage: "../cardImages/hearts-4.png",
  },
  {
    cardType: "5",
    cardValue: 5,
    suit: "hearts",
    cardImage: "../cardImages/hearts-5.png",
  },
  {
    cardType: "6",
    cardValue: 6,
    suit: "hearts",
    cardImage: "../cardImages/hearts-6.png",
  },
  {
    cardType: "7",
    cardValue: 7,
    suit: "hearts",
    cardImage: "../cardImages/hearts-7.png",
  },
  {
    cardType: "8",
    cardValue: 8,
    suit: "hearts",
    cardImage: "../cardImages/hearts-8.png",
  },
  {
    cardType: "9",
    cardValue: 9,
    suit: "hearts",
    cardImage: "../cardImages/hearts-9.png",
  },
  {
    cardType: "10",
    cardValue: 10,
    suit: "hearts",
    cardImage: "../cardImages/hearts-10.png",
  },
  {
    cardType: "J",
    cardValue: 10,
    suit: "hearts",
    cardImage: "../cardImages/hearts-J.png",
  },
  {
    cardType: "Q",
    cardValue: 10,
    suit: "hearts",
    cardImage: "../cardImages/hearts-Q.png",
  },
  {
    cardType: "K",
    cardValue: 10,
    suit: "hearts",
    cardImage: "../cardImages/hearts-K.png",
  },
];
